---
- hosts: k8s
  become: true
  vars:
    pod_cidr: "192.168.0.0/16"
    service_cidr: "10.96.0.0/12"
    local_cidr: "10.0.0.0/24"
    local: "127.0.0.1"
    proxy_ip: "10.0.0.1"
    proxy_port: "7890"

  tasks:
  - name: set proxy
    template:
      src: templates/proxy.j2
      dest: /etc/environment
