---
- hosts: k8s
  become: true
  vars:
    apiserver: "10.0.0.12"
    node1: "10.0.0.13"
    node2: "10.0.0.14"
  tasks:
    - name: set hostsfile
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
